
#Do

def CheckException(server_response):
	return server_response